default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres

development:
  <<: *default
  database: do_rails_development

test:
  <<: *default
  database: do_rails_test

production:
  <<: *default
  database: <%= ENV["MY_APP_DATABASE_DATABASE"] %>
  host: <%= ENV["MY_APP_DATABASE_HOST"] %>
  username: <%= ENV["MY_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["MY_APP_DATABASE_PASSWORD"] %>
